### ISSUE TITLE
Affichage chez vous

### ISSUE THREAD

**Issue by ChristGood** [GIorfindel/MasterMind#1]
J'ai lu ici : http://www.developpez.net/forums/d692314/java/interfaces-graphiques-java/awt-swing/fenetres-dialogues/couleur-fond-jbutton/
que l'affichage des composants de Swing et AWT peuvent changer selon l'OS. 
Est-ce que vous obtenez la même chose que ça : http://www.noelshack.com/2015-20-1431300252-fenetre.png ?

**Comment by GIorfindel** [comment]
Ca passe sous mac OS 
![capture d ecran 2015-05-11 a 09 32 20](https://cloud.githubusercontent.com/assets/5570743/7560245/8c221dbc-f7c1-11e4-906b-b56bd1110170.png)

**Comment by benTrust** [comment]
Sous debian ca passe. Sauf que Mon eclipse , dans la méthode creerBoutonMenu (dans Fenetre.java) la variable menuDestination j'ai du la mettre final(eclipse la fait tout seul!) car il m'indiquais une erreur.
